### ISSUE TITLE
bug in bef.portal.update.dataset ?

### ISSUE THREAD

**Issue by kej** [befdata/rbefdata#42]
I tried to update a dataset in development: 
![bug update dataset](https://cloud.githubusercontent.com/assets/1651747/3841930/bcd61d78-1e32-11e4-8c5f-5208d92c329e.jpg)

**Comment by Friessn** [comment]
Hey,
There is a bug in the code of rbefdata/rbefdata/R/bef.portal.upload.R
Line 77 says: 
postForm(paste0("http://befdataproduction.biow.uni-leipzig.de/datasets/", dataset_id, "/update_workbook")
should be: 
postForm(paste0(bef.options("url"), dataset_id, "/update_workbook")

Greetings,
Nico Friess

**Comment by cpfaff** [comment]
Thanks for highlighting this. Right there is a fixed URL coded where the options should be queried.
